FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /src/MeuPlantao.Infrastructure

ENTRYPOINT ["dotnet", "ef", "database", "update", "--startup-project", "../MeuPlantao.API"]