// <auto-generated />
using System;
using MeuPlantao.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeuPlantao.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321010001_AuthServices")]
    partial class AuthServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeuPlantao.Domain.Entities.PlantaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProfissionalResponsavelId")
                        .HasColumnType("bigint");

                    b.Property<long>("SetorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalResponsavelId");

                    b.HasIndex("SetorId");

                    b.ToTable("Plantoes");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.ProfissionalModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Crm")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.SetorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.TrocaHistoricoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Evento")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TrocaPlantaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrocaPlantaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.TrocaPlantaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DestinatarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PlantaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("SolicitanteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("PlantaoId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("TrocaPlantoes");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.PlantaoModel", b =>
                {
                    b.HasOne("MeuPlantao.Domain.Entities.ProfissionalModel", "ProfissionalResponsavel")
                        .WithMany()
                        .HasForeignKey("ProfissionalResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuPlantao.Domain.Entities.SetorModel", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfissionalResponsavel");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.ProfissionalModel", b =>
                {
                    b.HasOne("MeuPlantao.Domain.Entities.UserModel", "User")
                        .WithOne()
                        .HasForeignKey("MeuPlantao.Domain.Entities.ProfissionalModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.TrocaHistoricoModel", b =>
                {
                    b.HasOne("MeuPlantao.Domain.Entities.TrocaPlantaoModel", "TrocaPlantao")
                        .WithMany()
                        .HasForeignKey("TrocaPlantaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuPlantao.Domain.Entities.UserModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrocaPlantao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuPlantao.Domain.Entities.TrocaPlantaoModel", b =>
                {
                    b.HasOne("MeuPlantao.Domain.Entities.ProfissionalModel", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeuPlantao.Domain.Entities.PlantaoModel", "Plantao")
                        .WithMany()
                        .HasForeignKey("PlantaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuPlantao.Domain.Entities.ProfissionalModel", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Plantao");

                    b.Navigation("Solicitante");
                });
#pragma warning restore 612, 618
        }
    }
}
